# Generated by Django 4.2.1 on 2023-06-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloggers',
            options={'verbose_name': 'this is a test', 'verbose_name_plural': 'this is a test'},
        ),
        migrations.AddField(
            model_name='bloggers',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Blogger'),
        ),
        migrations.AddField(
            model_name='bloggers',
            name='name_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Blogger'),
        ),
        migrations.AddField(
            model_name='bloggers',
            name='text_en',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='bloggers',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='text'),
        ),
    ]
